databaseChangeLog:
  - changeSet:
      id: insert_values_movies-1
      author: Vladimir
      changes:
        - sql:
            sql: INSERT INTO movies (id, title, duration_in_min) VALUES ('${movie.terminator-2.id}', 'Terminator-2', 120)
        - sql:
            sql: INSERT INTO movies (id, title, duration_in_min) VALUES ('${movie.robocop.id}', 'Robocop', 112);